package OntologiaOrcamentoFederal;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Exercicio <br>
 * @version generated on Tue Apr 18 15:42:56 BOT 2017 by kennedy
 */

public interface Exercicio extends WrappedIndividual {

    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#identificador
     */
     
    /**
     * Gets all property values for the identificador property.<p>
     * 
     * @returns a collection of values for the identificador property.
     */
    Collection<? extends String> getIdentificador();

    /**
     * Checks if the class has a identificador property value.<p>
     * 
     * @return true if there is a identificador property value.
     */
    boolean hasIdentificador();

    /**
     * Adds a identificador property value.<p>
     * 
     * @param newIdentificador the identificador property value to be added
     */
    void addIdentificador(String newIdentificador);

    /**
     * Removes a identificador property value.<p>
     * 
     * @param oldIdentificador the identificador property value to be removed.
     */
    void removeIdentificador(String oldIdentificador);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
