package OntologiaOrcamentoFederal;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: ItemDespesa <br>
 * @version generated on Tue Apr 18 15:42:56 BOT 2017 by kennedy
 */

public interface ItemDespesa extends WrappedIndividual {

    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temAcao
     */
     
    /**
     * Gets all property values for the temAcao property.<p>
     * 
     * @returns a collection of values for the temAcao property.
     */
    Collection<? extends Acao> getTemAcao();

    /**
     * Checks if the class has a temAcao property value.<p>
     * 
     * @return true if there is a temAcao property value.
     */
    boolean hasTemAcao();

    /**
     * Adds a temAcao property value.<p>
     * 
     * @param newTemAcao the temAcao property value to be added
     */
    void addTemAcao(Acao newTemAcao);

    /**
     * Removes a temAcao property value.<p>
     * 
     * @param oldTemAcao the temAcao property value to be removed.
     */
    void removeTemAcao(Acao oldTemAcao);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temCategoriaEconomica
     */
     
    /**
     * Gets all property values for the temCategoriaEconomica property.<p>
     * 
     * @returns a collection of values for the temCategoriaEconomica property.
     */
    Collection<? extends CategoriaEconomica> getTemCategoriaEconomica();

    /**
     * Checks if the class has a temCategoriaEconomica property value.<p>
     * 
     * @return true if there is a temCategoriaEconomica property value.
     */
    boolean hasTemCategoriaEconomica();

    /**
     * Adds a temCategoriaEconomica property value.<p>
     * 
     * @param newTemCategoriaEconomica the temCategoriaEconomica property value to be added
     */
    void addTemCategoriaEconomica(CategoriaEconomica newTemCategoriaEconomica);

    /**
     * Removes a temCategoriaEconomica property value.<p>
     * 
     * @param oldTemCategoriaEconomica the temCategoriaEconomica property value to be removed.
     */
    void removeTemCategoriaEconomica(CategoriaEconomica oldTemCategoriaEconomica);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temClassificador
     */
     
    /**
     * Gets all property values for the temClassificador property.<p>
     * 
     * @returns a collection of values for the temClassificador property.
     */
    Collection<? extends Classificador> getTemClassificador();

    /**
     * Checks if the class has a temClassificador property value.<p>
     * 
     * @return true if there is a temClassificador property value.
     */
    boolean hasTemClassificador();

    /**
     * Adds a temClassificador property value.<p>
     * 
     * @param newTemClassificador the temClassificador property value to be added
     */
    void addTemClassificador(Classificador newTemClassificador);

    /**
     * Removes a temClassificador property value.<p>
     * 
     * @param oldTemClassificador the temClassificador property value to be removed.
     */
    void removeTemClassificador(Classificador oldTemClassificador);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temElementoDespesa
     */
     
    /**
     * Gets all property values for the temElementoDespesa property.<p>
     * 
     * @returns a collection of values for the temElementoDespesa property.
     */
    Collection<? extends ElementoDespesa> getTemElementoDespesa();

    /**
     * Checks if the class has a temElementoDespesa property value.<p>
     * 
     * @return true if there is a temElementoDespesa property value.
     */
    boolean hasTemElementoDespesa();

    /**
     * Adds a temElementoDespesa property value.<p>
     * 
     * @param newTemElementoDespesa the temElementoDespesa property value to be added
     */
    void addTemElementoDespesa(ElementoDespesa newTemElementoDespesa);

    /**
     * Removes a temElementoDespesa property value.<p>
     * 
     * @param oldTemElementoDespesa the temElementoDespesa property value to be removed.
     */
    void removeTemElementoDespesa(ElementoDespesa oldTemElementoDespesa);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temEsfera
     */
     
    /**
     * Gets all property values for the temEsfera property.<p>
     * 
     * @returns a collection of values for the temEsfera property.
     */
    Collection<? extends Esfera> getTemEsfera();

    /**
     * Checks if the class has a temEsfera property value.<p>
     * 
     * @return true if there is a temEsfera property value.
     */
    boolean hasTemEsfera();

    /**
     * Adds a temEsfera property value.<p>
     * 
     * @param newTemEsfera the temEsfera property value to be added
     */
    void addTemEsfera(Esfera newTemEsfera);

    /**
     * Removes a temEsfera property value.<p>
     * 
     * @param oldTemEsfera the temEsfera property value to be removed.
     */
    void removeTemEsfera(Esfera oldTemEsfera);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temExercicio
     */
     
    /**
     * Gets all property values for the temExercicio property.<p>
     * 
     * @returns a collection of values for the temExercicio property.
     */
    Collection<? extends Exercicio> getTemExercicio();

    /**
     * Checks if the class has a temExercicio property value.<p>
     * 
     * @return true if there is a temExercicio property value.
     */
    boolean hasTemExercicio();

    /**
     * Adds a temExercicio property value.<p>
     * 
     * @param newTemExercicio the temExercicio property value to be added
     */
    void addTemExercicio(Exercicio newTemExercicio);

    /**
     * Removes a temExercicio property value.<p>
     * 
     * @param oldTemExercicio the temExercicio property value to be removed.
     */
    void removeTemExercicio(Exercicio oldTemExercicio);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temFonteRecursos
     */
     
    /**
     * Gets all property values for the temFonteRecursos property.<p>
     * 
     * @returns a collection of values for the temFonteRecursos property.
     */
    Collection<? extends FonteRecursos> getTemFonteRecursos();

    /**
     * Checks if the class has a temFonteRecursos property value.<p>
     * 
     * @return true if there is a temFonteRecursos property value.
     */
    boolean hasTemFonteRecursos();

    /**
     * Adds a temFonteRecursos property value.<p>
     * 
     * @param newTemFonteRecursos the temFonteRecursos property value to be added
     */
    void addTemFonteRecursos(FonteRecursos newTemFonteRecursos);

    /**
     * Removes a temFonteRecursos property value.<p>
     * 
     * @param oldTemFonteRecursos the temFonteRecursos property value to be removed.
     */
    void removeTemFonteRecursos(FonteRecursos oldTemFonteRecursos);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temFuncao
     */
     
    /**
     * Gets all property values for the temFuncao property.<p>
     * 
     * @returns a collection of values for the temFuncao property.
     */
    Collection<? extends Funcao> getTemFuncao();

    /**
     * Checks if the class has a temFuncao property value.<p>
     * 
     * @return true if there is a temFuncao property value.
     */
    boolean hasTemFuncao();

    /**
     * Adds a temFuncao property value.<p>
     * 
     * @param newTemFuncao the temFuncao property value to be added
     */
    void addTemFuncao(Funcao newTemFuncao);

    /**
     * Removes a temFuncao property value.<p>
     * 
     * @param oldTemFuncao the temFuncao property value to be removed.
     */
    void removeTemFuncao(Funcao oldTemFuncao);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temGnd
     */
     
    /**
     * Gets all property values for the temGnd property.<p>
     * 
     * @returns a collection of values for the temGnd property.
     */
    Collection<? extends GrupoNatDespesa> getTemGnd();

    /**
     * Checks if the class has a temGnd property value.<p>
     * 
     * @return true if there is a temGnd property value.
     */
    boolean hasTemGnd();

    /**
     * Adds a temGnd property value.<p>
     * 
     * @param newTemGnd the temGnd property value to be added
     */
    void addTemGnd(GrupoNatDespesa newTemGnd);

    /**
     * Removes a temGnd property value.<p>
     * 
     * @param oldTemGnd the temGnd property value to be removed.
     */
    void removeTemGnd(GrupoNatDespesa oldTemGnd);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temIdentificadorUSO
     */
     
    /**
     * Gets all property values for the temIdentificadorUSO property.<p>
     * 
     * @returns a collection of values for the temIdentificadorUSO property.
     */
    Collection<? extends IdentificadorUSO> getTemIdentificadorUSO();

    /**
     * Checks if the class has a temIdentificadorUSO property value.<p>
     * 
     * @return true if there is a temIdentificadorUSO property value.
     */
    boolean hasTemIdentificadorUSO();

    /**
     * Adds a temIdentificadorUSO property value.<p>
     * 
     * @param newTemIdentificadorUSO the temIdentificadorUSO property value to be added
     */
    void addTemIdentificadorUSO(IdentificadorUSO newTemIdentificadorUSO);

    /**
     * Removes a temIdentificadorUSO property value.<p>
     * 
     * @param oldTemIdentificadorUSO the temIdentificadorUSO property value to be removed.
     */
    void removeTemIdentificadorUSO(IdentificadorUSO oldTemIdentificadorUSO);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temModalidadeAplicacao
     */
     
    /**
     * Gets all property values for the temModalidadeAplicacao property.<p>
     * 
     * @returns a collection of values for the temModalidadeAplicacao property.
     */
    Collection<? extends ModalidadeAplicacao> getTemModalidadeAplicacao();

    /**
     * Checks if the class has a temModalidadeAplicacao property value.<p>
     * 
     * @return true if there is a temModalidadeAplicacao property value.
     */
    boolean hasTemModalidadeAplicacao();

    /**
     * Adds a temModalidadeAplicacao property value.<p>
     * 
     * @param newTemModalidadeAplicacao the temModalidadeAplicacao property value to be added
     */
    void addTemModalidadeAplicacao(ModalidadeAplicacao newTemModalidadeAplicacao);

    /**
     * Removes a temModalidadeAplicacao property value.<p>
     * 
     * @param oldTemModalidadeAplicacao the temModalidadeAplicacao property value to be removed.
     */
    void removeTemModalidadeAplicacao(ModalidadeAplicacao oldTemModalidadeAplicacao);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temPlanoOrcamentario
     */
     
    /**
     * Gets all property values for the temPlanoOrcamentario property.<p>
     * 
     * @returns a collection of values for the temPlanoOrcamentario property.
     */
    Collection<? extends PlanoOrcamentario> getTemPlanoOrcamentario();

    /**
     * Checks if the class has a temPlanoOrcamentario property value.<p>
     * 
     * @return true if there is a temPlanoOrcamentario property value.
     */
    boolean hasTemPlanoOrcamentario();

    /**
     * Adds a temPlanoOrcamentario property value.<p>
     * 
     * @param newTemPlanoOrcamentario the temPlanoOrcamentario property value to be added
     */
    void addTemPlanoOrcamentario(PlanoOrcamentario newTemPlanoOrcamentario);

    /**
     * Removes a temPlanoOrcamentario property value.<p>
     * 
     * @param oldTemPlanoOrcamentario the temPlanoOrcamentario property value to be removed.
     */
    void removeTemPlanoOrcamentario(PlanoOrcamentario oldTemPlanoOrcamentario);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temPrograma
     */
     
    /**
     * Gets all property values for the temPrograma property.<p>
     * 
     * @returns a collection of values for the temPrograma property.
     */
    Collection<? extends Programa> getTemPrograma();

    /**
     * Checks if the class has a temPrograma property value.<p>
     * 
     * @return true if there is a temPrograma property value.
     */
    boolean hasTemPrograma();

    /**
     * Adds a temPrograma property value.<p>
     * 
     * @param newTemPrograma the temPrograma property value to be added
     */
    void addTemPrograma(Programa newTemPrograma);

    /**
     * Removes a temPrograma property value.<p>
     * 
     * @param oldTemPrograma the temPrograma property value to be removed.
     */
    void removeTemPrograma(Programa oldTemPrograma);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temResultadoPrimario
     */
     
    /**
     * Gets all property values for the temResultadoPrimario property.<p>
     * 
     * @returns a collection of values for the temResultadoPrimario property.
     */
    Collection<? extends ResultadoPrimario> getTemResultadoPrimario();

    /**
     * Checks if the class has a temResultadoPrimario property value.<p>
     * 
     * @return true if there is a temResultadoPrimario property value.
     */
    boolean hasTemResultadoPrimario();

    /**
     * Adds a temResultadoPrimario property value.<p>
     * 
     * @param newTemResultadoPrimario the temResultadoPrimario property value to be added
     */
    void addTemResultadoPrimario(ResultadoPrimario newTemResultadoPrimario);

    /**
     * Removes a temResultadoPrimario property value.<p>
     * 
     * @param oldTemResultadoPrimario the temResultadoPrimario property value to be removed.
     */
    void removeTemResultadoPrimario(ResultadoPrimario oldTemResultadoPrimario);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temSubFuncao
     */
     
    /**
     * Gets all property values for the temSubFuncao property.<p>
     * 
     * @returns a collection of values for the temSubFuncao property.
     */
    Collection<? extends Subfuncao> getTemSubFuncao();

    /**
     * Checks if the class has a temSubFuncao property value.<p>
     * 
     * @return true if there is a temSubFuncao property value.
     */
    boolean hasTemSubFuncao();

    /**
     * Adds a temSubFuncao property value.<p>
     * 
     * @param newTemSubFuncao the temSubFuncao property value to be added
     */
    void addTemSubFuncao(Subfuncao newTemSubFuncao);

    /**
     * Removes a temSubFuncao property value.<p>
     * 
     * @param oldTemSubFuncao the temSubFuncao property value to be removed.
     */
    void removeTemSubFuncao(Subfuncao oldTemSubFuncao);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temSubtitulo
     */
     
    /**
     * Gets all property values for the temSubtitulo property.<p>
     * 
     * @returns a collection of values for the temSubtitulo property.
     */
    Collection<? extends Subtitulo> getTemSubtitulo();

    /**
     * Checks if the class has a temSubtitulo property value.<p>
     * 
     * @return true if there is a temSubtitulo property value.
     */
    boolean hasTemSubtitulo();

    /**
     * Adds a temSubtitulo property value.<p>
     * 
     * @param newTemSubtitulo the temSubtitulo property value to be added
     */
    void addTemSubtitulo(Subtitulo newTemSubtitulo);

    /**
     * Removes a temSubtitulo property value.<p>
     * 
     * @param oldTemSubtitulo the temSubtitulo property value to be removed.
     */
    void removeTemSubtitulo(Subtitulo oldTemSubtitulo);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#temUnidadeOrcamentaria
     */
     
    /**
     * Gets all property values for the temUnidadeOrcamentaria property.<p>
     * 
     * @returns a collection of values for the temUnidadeOrcamentaria property.
     */
    Collection<? extends UnidadeOrcamentaria> getTemUnidadeOrcamentaria();

    /**
     * Checks if the class has a temUnidadeOrcamentaria property value.<p>
     * 
     * @return true if there is a temUnidadeOrcamentaria property value.
     */
    boolean hasTemUnidadeOrcamentaria();

    /**
     * Adds a temUnidadeOrcamentaria property value.<p>
     * 
     * @param newTemUnidadeOrcamentaria the temUnidadeOrcamentaria property value to be added
     */
    void addTemUnidadeOrcamentaria(UnidadeOrcamentaria newTemUnidadeOrcamentaria);

    /**
     * Removes a temUnidadeOrcamentaria property value.<p>
     * 
     * @param oldTemUnidadeOrcamentaria the temUnidadeOrcamentaria property value to be removed.
     */
    void removeTemUnidadeOrcamentaria(UnidadeOrcamentaria oldTemUnidadeOrcamentaria);


    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#valorDotacaoInicial
     */
     
    /**
     * Gets all property values for the valorDotacaoInicial property.<p>
     * 
     * @returns a collection of values for the valorDotacaoInicial property.
     */
    Collection<? extends Object> getValorDotacaoInicial();

    /**
     * Checks if the class has a valorDotacaoInicial property value.<p>
     * 
     * @return true if there is a valorDotacaoInicial property value.
     */
    boolean hasValorDotacaoInicial();

    /**
     * Adds a valorDotacaoInicial property value.<p>
     * 
     * @param newValorDotacaoInicial the valorDotacaoInicial property value to be added
     */
    void addValorDotacaoInicial(Object newValorDotacaoInicial);

    /**
     * Removes a valorDotacaoInicial property value.<p>
     * 
     * @param oldValorDotacaoInicial the valorDotacaoInicial property value to be removed.
     */
    void removeValorDotacaoInicial(Object oldValorDotacaoInicial);



    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#valorEmpenhado
     */
     
    /**
     * Gets all property values for the valorEmpenhado property.<p>
     * 
     * @returns a collection of values for the valorEmpenhado property.
     */
    Collection<? extends Object> getValorEmpenhado();

    /**
     * Checks if the class has a valorEmpenhado property value.<p>
     * 
     * @return true if there is a valorEmpenhado property value.
     */
    boolean hasValorEmpenhado();

    /**
     * Adds a valorEmpenhado property value.<p>
     * 
     * @param newValorEmpenhado the valorEmpenhado property value to be added
     */
    void addValorEmpenhado(Object newValorEmpenhado);

    /**
     * Removes a valorEmpenhado property value.<p>
     * 
     * @param oldValorEmpenhado the valorEmpenhado property value to be removed.
     */
    void removeValorEmpenhado(Object oldValorEmpenhado);



    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#valorLeiMaisCreditos
     */
     
    /**
     * Gets all property values for the valorLeiMaisCreditos property.<p>
     * 
     * @returns a collection of values for the valorLeiMaisCreditos property.
     */
    Collection<? extends Object> getValorLeiMaisCreditos();

    /**
     * Checks if the class has a valorLeiMaisCreditos property value.<p>
     * 
     * @return true if there is a valorLeiMaisCreditos property value.
     */
    boolean hasValorLeiMaisCreditos();

    /**
     * Adds a valorLeiMaisCreditos property value.<p>
     * 
     * @param newValorLeiMaisCreditos the valorLeiMaisCreditos property value to be added
     */
    void addValorLeiMaisCreditos(Object newValorLeiMaisCreditos);

    /**
     * Removes a valorLeiMaisCreditos property value.<p>
     * 
     * @param oldValorLeiMaisCreditos the valorLeiMaisCreditos property value to be removed.
     */
    void removeValorLeiMaisCreditos(Object oldValorLeiMaisCreditos);



    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#valorLiquidado
     */
     
    /**
     * Gets all property values for the valorLiquidado property.<p>
     * 
     * @returns a collection of values for the valorLiquidado property.
     */
    Collection<? extends Object> getValorLiquidado();

    /**
     * Checks if the class has a valorLiquidado property value.<p>
     * 
     * @return true if there is a valorLiquidado property value.
     */
    boolean hasValorLiquidado();

    /**
     * Adds a valorLiquidado property value.<p>
     * 
     * @param newValorLiquidado the valorLiquidado property value to be added
     */
    void addValorLiquidado(Object newValorLiquidado);

    /**
     * Removes a valorLiquidado property value.<p>
     * 
     * @param oldValorLiquidado the valorLiquidado property value to be removed.
     */
    void removeValorLiquidado(Object oldValorLiquidado);



    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#valorPago
     */
     
    /**
     * Gets all property values for the valorPago property.<p>
     * 
     * @returns a collection of values for the valorPago property.
     */
    Collection<? extends Object> getValorPago();

    /**
     * Checks if the class has a valorPago property value.<p>
     * 
     * @return true if there is a valorPago property value.
     */
    boolean hasValorPago();

    /**
     * Adds a valorPago property value.<p>
     * 
     * @param newValorPago the valorPago property value to be added
     */
    void addValorPago(Object newValorPago);

    /**
     * Removes a valorPago property value.<p>
     * 
     * @param oldValorPago the valorPago property value to be removed.
     */
    void removeValorPago(Object oldValorPago);



    /* ***************************************************
     * Property https://github.com/kennedyrs/orcamento-federal#valorProjetoLei
     */
     
    /**
     * Gets all property values for the valorProjetoLei property.<p>
     * 
     * @returns a collection of values for the valorProjetoLei property.
     */
    Collection<? extends Object> getValorProjetoLei();

    /**
     * Checks if the class has a valorProjetoLei property value.<p>
     * 
     * @return true if there is a valorProjetoLei property value.
     */
    boolean hasValorProjetoLei();

    /**
     * Adds a valorProjetoLei property value.<p>
     * 
     * @param newValorProjetoLei the valorProjetoLei property value to be added
     */
    void addValorProjetoLei(Object newValorProjetoLei);

    /**
     * Removes a valorProjetoLei property value.<p>
     * 
     * @param oldValorProjetoLei the valorProjetoLei property value to be removed.
     */
    void removeValorProjetoLei(Object oldValorProjetoLei);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
