package OntologiaOrcamentoFederal;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Tue Apr 18 15:42:56 BOT 2017 by kennedy
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#Acao
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACAO.<p>
     * 
     */
    public static final OWLClass CLASS_ACAO = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#Acao"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#Atividade
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATIVIDADE.<p>
     * 
     */
    public static final OWLClass CLASS_ATIVIDADE = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#Atividade"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#CategoriaEconomica
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CATEGORIAECONOMICA.<p>
     * 
     */
    public static final OWLClass CLASS_CATEGORIAECONOMICA = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#CategoriaEconomica"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#Classificador
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CLASSIFICADOR.<p>
     * 
     */
    public static final OWLClass CLASS_CLASSIFICADOR = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#Classificador"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#ElementoDespesa
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ELEMENTODESPESA.<p>
     * 
     */
    public static final OWLClass CLASS_ELEMENTODESPESA = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#ElementoDespesa"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#Esfera
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ESFERA.<p>
     * 
     */
    public static final OWLClass CLASS_ESFERA = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#Esfera"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#Exercicio
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXERCICIO.<p>
     * 
     */
    public static final OWLClass CLASS_EXERCICIO = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#Exercicio"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#FonteRecursos
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FONTERECURSOS.<p>
     * 
     */
    public static final OWLClass CLASS_FONTERECURSOS = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#FonteRecursos"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#Funcao
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FUNCAO.<p>
     * 
     */
    public static final OWLClass CLASS_FUNCAO = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#Funcao"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#GrupoNatDespesa
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GRUPONATDESPESA.<p>
     * 
     */
    public static final OWLClass CLASS_GRUPONATDESPESA = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#GrupoNatDespesa"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#IdentificadorUSO
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IDENTIFICADORUSO.<p>
     * 
     */
    public static final OWLClass CLASS_IDENTIFICADORUSO = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#IdentificadorUSO"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#ItemDespesa
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ITEMDESPESA.<p>
     * 
     */
    public static final OWLClass CLASS_ITEMDESPESA = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#ItemDespesa"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#ModalidadeAplicacao
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MODALIDADEAPLICACAO.<p>
     * 
     */
    public static final OWLClass CLASS_MODALIDADEAPLICACAO = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#ModalidadeAplicacao"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#OperacaoEspecial
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OPERACAOESPECIAL.<p>
     * 
     */
    public static final OWLClass CLASS_OPERACAOESPECIAL = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#OperacaoEspecial"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#Orgao
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ORGAO.<p>
     * 
     */
    public static final OWLClass CLASS_ORGAO = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#Orgao"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#PlanoOrcamentario
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PLANOORCAMENTARIO.<p>
     * 
     */
    public static final OWLClass CLASS_PLANOORCAMENTARIO = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#PlanoOrcamentario"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#Programa
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROGRAMA.<p>
     * 
     */
    public static final OWLClass CLASS_PROGRAMA = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#Programa"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#Projeto
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJETO.<p>
     * 
     */
    public static final OWLClass CLASS_PROJETO = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#Projeto"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#ResultadoPrimario
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESULTADOPRIMARIO.<p>
     * 
     */
    public static final OWLClass CLASS_RESULTADOPRIMARIO = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#ResultadoPrimario"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#Subfuncao
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SUBFUNCAO.<p>
     * 
     */
    public static final OWLClass CLASS_SUBFUNCAO = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#Subfuncao"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#Subtitulo
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SUBTITULO.<p>
     * 
     */
    public static final OWLClass CLASS_SUBTITULO = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#Subtitulo"));

    /* ***************************************************
     * Class https://github.com/kennedyrs/orcamento-federal#UnidadeOrcamentaria
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class UNIDADEORCAMENTARIA.<p>
     * 
     */
    public static final OWLClass CLASS_UNIDADEORCAMENTARIA = factory.getOWLClass(IRI.create("https://github.com/kennedyrs/orcamento-federal#UnidadeOrcamentaria"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temAcao
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMACAO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMACAO = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temAcao"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temCategoriaEconomica
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMCATEGORIAECONOMICA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMCATEGORIAECONOMICA = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temCategoriaEconomica"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temClassificador
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMCLASSIFICADOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMCLASSIFICADOR = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temClassificador"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temElementoDespesa
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMELEMENTODESPESA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMELEMENTODESPESA = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temElementoDespesa"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temEsfera
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMESFERA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMESFERA = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temEsfera"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temExercicio
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMEXERCICIO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMEXERCICIO = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temExercicio"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temFonteRecursos
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMFONTERECURSOS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMFONTERECURSOS = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temFonteRecursos"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temFuncao
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMFUNCAO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMFUNCAO = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temFuncao"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temGnd
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMGND.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMGND = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temGnd"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temIdentificadorUSO
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMIDENTIFICADORUSO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMIDENTIFICADORUSO = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temIdentificadorUSO"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temModalidadeAplicacao
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMMODALIDADEAPLICACAO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMMODALIDADEAPLICACAO = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temModalidadeAplicacao"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temOrgao
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMORGAO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMORGAO = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temOrgao"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temPlanoOrcamentario
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMPLANOORCAMENTARIO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMPLANOORCAMENTARIO = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temPlanoOrcamentario"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temPrograma
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMPROGRAMA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMPROGRAMA = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temPrograma"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temResultadoPrimario
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMRESULTADOPRIMARIO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMRESULTADOPRIMARIO = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temResultadoPrimario"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temSubFuncao
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMSUBFUNCAO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMSUBFUNCAO = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temSubFuncao"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temSubtitulo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMSUBTITULO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMSUBTITULO = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temSubtitulo"));

    /* ***************************************************
     * Object Property https://github.com/kennedyrs/orcamento-federal#temUnidadeOrcamentaria
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TEMUNIDADEORCAMENTARIA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TEMUNIDADEORCAMENTARIA = factory.getOWLObjectProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#temUnidadeOrcamentaria"));

    /* ***************************************************
     * Data Property https://github.com/kennedyrs/orcamento-federal#codigo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CODIGO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CODIGO = factory.getOWLDataProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#codigo"));

    /* ***************************************************
     * Data Property https://github.com/kennedyrs/orcamento-federal#dataAtualizacao
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DATAATUALIZACAO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DATAATUALIZACAO = factory.getOWLDataProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#dataAtualizacao"));

    /* ***************************************************
     * Data Property https://github.com/kennedyrs/orcamento-federal#identificador
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property IDENTIFICADOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_IDENTIFICADOR = factory.getOWLDataProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#identificador"));

    /* ***************************************************
     * Data Property https://github.com/kennedyrs/orcamento-federal#label
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LABEL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LABEL = factory.getOWLDataProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#label"));

    /* ***************************************************
     * Data Property https://github.com/kennedyrs/orcamento-federal#valorDotacaoInicial
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VALORDOTACAOINICIAL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VALORDOTACAOINICIAL = factory.getOWLDataProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#valorDotacaoInicial"));

    /* ***************************************************
     * Data Property https://github.com/kennedyrs/orcamento-federal#valorEmpenhado
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VALOREMPENHADO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VALOREMPENHADO = factory.getOWLDataProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#valorEmpenhado"));

    /* ***************************************************
     * Data Property https://github.com/kennedyrs/orcamento-federal#valorLeiMaisCreditos
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VALORLEIMAISCREDITOS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VALORLEIMAISCREDITOS = factory.getOWLDataProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#valorLeiMaisCreditos"));

    /* ***************************************************
     * Data Property https://github.com/kennedyrs/orcamento-federal#valorLiquidado
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VALORLIQUIDADO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VALORLIQUIDADO = factory.getOWLDataProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#valorLiquidado"));

    /* ***************************************************
     * Data Property https://github.com/kennedyrs/orcamento-federal#valorPago
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VALORPAGO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VALORPAGO = factory.getOWLDataProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#valorPago"));

    /* ***************************************************
     * Data Property https://github.com/kennedyrs/orcamento-federal#valorProjetoLei
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VALORPROJETOLEI.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VALORPROJETOLEI = factory.getOWLDataProperty(IRI.create("https://github.com/kennedyrs/orcamento-federal#valorProjetoLei"));


}
