package OntologiaOrcamentoFederal.impl;

import OntologiaOrcamentoFederal.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultExercicio <br>
 * @version generated on Tue Apr 18 15:42:56 BOT 2017 by kennedy
 */
public class DefaultExercicio extends WrappedIndividualImpl implements Exercicio {

    public DefaultExercicio(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property https://github.com/kennedyrs/orcamento-federal#identificador
     */
     
    public Collection<? extends String> getIdentificador() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_IDENTIFICADOR, String.class);
    }

    public boolean hasIdentificador() {
		return !getIdentificador().isEmpty();
    }

    public void addIdentificador(String newIdentificador) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_IDENTIFICADOR, newIdentificador);
    }

    public void removeIdentificador(String oldIdentificador) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_IDENTIFICADOR, oldIdentificador);
    }


}
