package OntologiaOrcamentoFederal.impl;

import OntologiaOrcamentoFederal.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultOrgao <br>
 * @version generated on Tue Apr 18 15:42:57 BOT 2017 by kennedy
 */
public class DefaultOrgao extends WrappedIndividualImpl implements Orgao {

    public DefaultOrgao(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
